Fix javadoc error with '>' character
Using '>' in the javadoc string throws an error when building with Java
13:

synthea\src\main\java\org\mitre\synthea\helpers\Utilities.java:373: error: bad use of '>'
   *        (currentModulePath) -> {...}

The character was replaced with HTML equivalent "&gt;". Although that is
not very elegant, it is the least invasive fix I found for this issue.